### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by rpmanser** [ac0015/wrf-ens-tools#20]
When setting up the environment and installing I run into some errors. I setup and install with the following:

```bash
$ conda env create -f environment.yml
$ source activate wrf-devel
$ python setup.py install
```

Installing fails because there is a conflict with the `pyproj` module installed from `environment.yml` and the required `pyproj` versions for `metpy` 1.0. I suggest we specify `metpy==0.12.2` and upgrade to 1.0 in a separate issue/PR.

When I run the test suite, the following modules are missing:
`cmocean`
`dask[array]`

Which is fixed by adding them to `setupy.py`.

**Comment by tjwixtrom** [comment]
I have a version that should fix this, I'll try to get in a PR this week. We need to move to MetPy 1.0 for some of the WRF processing functions to work.
